### ISSUE TITLE
Implement truename command

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/comcom64#100]
Here's the syntax that FreeCOM implements
~~~
C:\>truename /?
Displays the full path name of the path specified.
 
TRUENAME [drive:][path][filename]
~~~

It should try int21/7160 first then fall back to int21/60 if that's not available.

**Comment by stsp** [comment]
What does it actually give us?

Воскресенье, 25 августа 2024 г получено от Andrew Bird:

**Comment by andrewbird** [comment]
Compatibility with other DOSes.

**Comment by stsp** [comment]
Which ones, but freecom?
(which is not a dos)

**Comment by andrewbird** [comment]
MS-DOS 5 and up have it. It's not really important though, I'll close.

**Comment by stsp** [comment]
msdos compatibility is ok.
