### ISSUE TITLE
mouse integration

### ISSUE THREAD

**Issue by stsp** [dosemu2/comcom64#16]
It would be very interesting to have a mouse
integration. You can move the cursor in a cmd
line by the mouse left-click. You can scroll the
history buffer with the wheel. You can do the
tab-like completion with the right-click.

**Comment by JL2210** [comment]
Are you familiar with BIOS interrupts? There is one that I use (`int $0x33` in GAS, `int 33h` otherwise) that manipulates the mouse. See http://www.ctyme.com/intr/int-33.htm

**Comment by stsp** [comment]
Should I ban you for the useless comments? :(

**Comment by JL2210** [comment]
No. I was legitimately trying to be helpful. Shouldn't you be able to manipulate the mouse with that BIOS/DOS interrupt/

**Comment by JL2210** [comment]
You seem to know something about the topic: https://github.com/stsp/win31-mouse-driver

Can I help with this?

**Comment by stsp** [comment]
I don't think you can.
But if you create the patch and open a
pull request, then I'll be surprised.
Otherwise you are under the big risk of
being banned.

**Comment by JL2210** [comment]
Well, thank you. I appreciate the hostility :).

What needs to be done for this to work? I haven't found anything related to the scrolling of the mouse.

**Comment by JL2210** [comment]
Just putting this here as a note for later: https://wiki.osdev.org/Mouse_Input

It has some interesting information.

**Comment by stsp** [comment]
> I haven't found anything related to the scrolling of the mouse.

Where? In comcom32 there is no mouse code at all.
It needs to be written.
But in int33 it is available and can be used according
to this specification:
https://sourceforge.net/p/cutemouse/trunk/ci/master/tree/ctm-2/doc/wheelapi.txt

**Comment by JL2210** [comment]
Thanks. I'll read up on that tomorrow. For now, though, I need to get some sleep.
