### ISSUE TITLE
exec command line limited to 126 bytes

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/comcom64#31]
Batch files have a limit of 127 bytes per line with unexpanded environment variables. With environment variables expanded, this is much larger, but with comcom32 it is still 127 bytes. This causes batch files like my FreeDOS installation script to fail in comcom32:
https://github.com/jschwartzenberg/dos-download-scripts/blob/master/dosemu/insfd12.bat

In FreeCom it does work correctly.

**Comment by jschwartzenberg** [comment]
This doesn't work yet. Maybe you can try my scripts to reproduce?

**Comment by stsp** [comment]
Yes, can reproduce.

**Comment by stsp** [comment]
There is no standard way in DOS to pass
such big cmdlines. There are some techniques
like `CMDLINE=` env var, but the DOS app should
be prepared to take the args from that var, and
unix.com is not.
There is a certain short-cut between freecom and
dosemu2 tools that allows to pass such a big cmd
lines directly, bypassing DOS exec. But you won't
be able to e.g. pass such a big cmdline to wget -
only to dosemu2 tools. Of course you got lucky that
unix.com passes that to wget under linux where there
is no such limit. So in your case things surprisingly
worked, but I'd say you were exceptionally lucky.
You won't get this to work on any other emulators
including dosemu1, but dosemu2 is full of surprises
even for me (i.e. I couldn't believe my eyes seeing
this works under freecom).
It is indeed impossible, but the aforementioned
short-cut for dosemu2 tools may eventually be added
to comcom32, see #10.

Another option is to declare `unix.com` special
and add an ability to it to take the cmdline from
`CMDLINE=` var. It is an arguably valid to assume
that only "unix.com" may need a very long command
lines.

**Comment by stsp** [comment]
> and add an ability to it to take the cmdline from
> CMDLINE= var

And that looks problematic as djgpp does this
trick only for shells (compares the program name
to the list of known shells). Otherwise it just
truncates the cmdline to 126 (not 127!) bytes,
so its quite difficult to get an indication that the
line was truncated (127 is such an indication).

**Comment by stsp** [comment]
Now you can pass long cmdlines
(up to 256 chars) to unix.com with
comcom64/32, similar to how it
was with freecom.
