### ISSUE TITLE
copy doesn't support concatenation

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/comcom64#42]
Some of the PC-MOS build files use concatenation to create a single larger file, but comcom32 doesn't seem to support this yet. I'm sure I can work around this, so there's no panic on my side to get this in, but I thought I'd open an issue so it doesn't get lost.

~~~
C:\>copy userhook.bat + emm386.exe bob.bin
Too many parameters - emm386.exe bob.bin
C:\>echo %errorlevel%
0
~~~

This doesn't stop the build process either, because as an internal command it doesn't seem to set ERRORLEVEL. I'm not sure if that's normal behaviour though as only recently I saw a similar report for FreeCOM https://github.com/FDOS/freecom/issues/28

**Comment by stsp** [comment]
Please consider fixing comcom32. :)
Its far less frightening than fdpp; in
fact, its very naively-coded.
