### ISSUE TITLE
cannot build in buster . because buster don't have gcc-djgpp

### ISSUE THREAD

**Issue by yuyue2013** [dosemu2/comcom64#45]
cannot build in buster . because buster don't have gcc-djgpp

**Comment by stsp** [comment]
Can you try the ubuntu PPA packages?
Maybe they will install on buster?

**Comment by yuyue2013** [comment]
can not. have error


> aitalmac@debian:~/PROGRAM/comcom32$ sudo add-apt-repository ppa:dosemu2/ppa
>  
>  More info: https://launchpad.net/~dosemu2/+archive/ubuntu/ppa
> Press [ENTER] to continue or ctrl-c to cancel adding it
> 
> gpg: keybox '/tmp/tmpbnpi953r/pubring.gpg' created
> gpg: /tmp/tmpbnpi953r/trustdb.gpg: trustdb created
> gpg: key EBE1B5DED2AD45D6: public key "Launchpad PPA for Dosemu2" imported
> gpg: Total number processed: 1
> gpg:               imported: 1
> gpg: no valid OpenPGP data found.
> aitalmac@debian:~/PROGRAM/comcom32$ sudo apt-get update
> Hit:1 http://packages.microsoft.com/repos/vscode stable InRelease
> Hit:2 http://linux.teamviewer.com/deb stable InRelease                         
> Hit:3 https://mirrors.tuna.tsinghua.edu.cn/debian buster InRelease             
> Hit:4 https://mirrors.tuna.tsinghua.edu.cn/debian buster-updates InRelease     
> Hit:5 https://mirrors.tuna.tsinghua.edu.cn/debian buster-backports InRelease
> Hit:6 http://repo.aptly.info nightly InRelease                           
> Get:7 http://ppa.launchpad.net/dosemu2/ppa/ubuntu groovy InRelease [24.3 kB]
> Get:8 https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates InRelease [65.4 kB]
> Err:7 http://ppa.launchpad.net/dosemu2/ppa/ubuntu groovy InRelease   
>   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBE1B5DED2AD45D6
> Reading package lists... Done
> W: GPG error: http://ppa.launchpad.net/dosemu2/ppa/ubuntu groovy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBE1B5DED2AD45D6
> E: The repository 'http://ppa.launchpad.net/dosemu2/ppa/ubuntu groovy InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by stsp** [comment]
You need to allow unauthenticated
repositories.

**Comment by stsp** [comment]
@skitt what is the status of djgpp in debian?
I suppose its not going to work that way and
I need to switch away from djgpp?

**Comment by skitt** [comment]
> @skitt what is the status of djgpp in debian?
> I suppose its not going to work that way and
> I need to switch away from djgpp?

Still working on it, I hope to get it in before the freeze (and dosemu2).

**Comment by tsuki-superior** [comment]
Do not use ubuntu ppas on debian, it may break your system

**Comment by tsuki-superior** [comment]
Just use this https://github.com/andrewwutw/build-djgpp and add the install location for the compiler to $PATH

**Comment by stsp** [comment]
Resolved.
