### ISSUE TITLE
`README.md`'s links to build tools does not work. Where to find `dj64-gcc`?

### ISSUE THREAD

**Issue by dreirund** [dosemu2/comcom64#90]
Ahoj,

I want to build `comcom64` on Arch Linux.  
It needs `dj64-gcc` executable.

I do not know where to find it, so I wanted to read [the lists of needed build tools which the `README.md` links for Ubuntu and Fedora](https://github.com/dosemu2/comcom64/blob/master/README.md?plain=1#L8-L12).

But the links do not work; they lead to an HTTP error 404 "Not Found".

In the [`README.md`](https://github.com/dosemu2/comcom64/blob/master/README.md?plain=1#L8-L12):

```markdown
Install the needed build tools.<br/>
You can see the list of them
[for ubuntu](https://github.com/stsp/comcom64/blob/master/debian/control#L7-L14)
or
[for fedora](https://github.com/stsp/comcom64/blob/master/comcom64.spec.rpkg#L17-L24)
```

Both URLs do not work.

Regards!

**Comment by stsp** [comment]
Links should now work, thanks!
Unfortunately comcom64 needs
too many build deps, which is why
I decided to keep supporting the
deprecated comcom32, until the
build deps are added to debian
at least.
So you are free to use either one
of comcoms for now.

**Comment by severach** [comment]
I got all the tools built for dj64. comcom64 is ready to go in Arch.

**Comment by stsp** [comment]
Interesting!
You may want to add this patch
to smallerc:
https://github.com/alexfru/SmallerC/pull/42
as the maintainer is a bit slow
to review.

**Comment by stsp** [comment]
Also please correct the home-page
of an lfanew:
https://codeberg.org/tkchia/lfanew
I put the fork on github only to add
debian/fedora build specs, so my
fork is irrelevant and should (preferably)
not be built.

**Comment by severach** [comment]
All set on those fixes.
