### ISSUE TITLE
copy con file doesn't work

### ISSUE THREAD

**Issue by stsp** [dosemu2/comcom64#93]
```
C:\>copy con aaa.txt
File(s) not found - c:\con
```

**Comment by stsp** [comment]
Fixed in dosemu2.
But I've found an additional problem
that `_crt0_startup_flags` are not supported
by dj64dev, so its not possible to switch
between lfn/sfn for testing...

**Comment by andrewbird** [comment]
So I can't do `set LFN=n` before running a djgpp `.exe` to disable or is it just in comcom?

**Comment by stsp** [comment]
That probably works.
Please check and tell. :)
`_crt0_startup_flags` are independent
of that and I'll see about adding them
even if LFN is controlable by other means.

**Comment by stsp** [comment]
`_crt0_startup_flags` is now supported
by dj64dev.
