### ISSUE TITLE
Openwatcom Wmake not creating FreeCOM config file

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/comcom64#97]
I think I've located the issue building FreeCOM under FDPP/Comcom. I've boiled the problem down to a small test case.

I have three files, two batch files and a makefile.
##### testit.bat
sets up the watcom env and path
calls wmake in ms make mode

##### makefile
has one target
deletes the output file
calls the second batchfile repeatedly to append to the output file
lists the output file
types the output file

##### echoto.bat
this is obtained from the FreeCOM project

-----------------------------------

#### procedure

1. unzip the attached file in your dosemu C: directory [t1.zip](https://github.com/dosemu2/comcom64/files/15148816/t1.zip)
2. it has the FreeDOS 1.3 `command.com` and the salient part of FreeDOS watcomc package there.
3. run the test `testit.bat`
4. See the expected output
5. now delete or rename `command.com` (and reboot)
6.  run the test `testit.bat`
7. See that the output file `watcomc.cfg` is not created

**Comment by stsp** [comment]
Grr, while debugging a single instance
of comcom64 with gdb is a pleasant
experience, in this particular case make
spawns new instances, and the debugging
is becoming quite messy.
I probably need to add some switch to
comcom64 to optionally work within a
single instance, to simplify debugging...

**Comment by stsp** [comment]
I think its a wmake bug.
It hooks int31 and doesn't chain back
the function 0xa00 (get vendor API).
Therefore comcom64 cannot load.

I can't find wmake sources. In ow2 tree
there are binaries!
So I give up.

**Comment by stsp** [comment]
Ah, actually its a dos4gw bug!
If you copy dos32a instead of dos4gw,
then things work.

**Comment by stsp** [comment]
So here's the fix:
`set DOS4GPATH=c:\devel\watcomc\binw\dos32a.exe`

**Comment by andrewbird** [comment]
Thank you, that fixed the FreeCOM build test on FDPP/Comcom. It still fails on MS-DOS due to out of environment space (even though I increased it in stages all the way up to 4096), so for now I marked it as a known fail and will it be skipped. If you think that it's possible that Dosemu could be at fault I could investigate developing a simple test case, otherwise I'll just accept that it's broken and submit the PR as is?

**Comment by stsp** [comment]
Does it work under any other emulator
or pc?

**Comment by stsp** [comment]
Also is it only ms-dos, or any non-fdpp dos?

**Comment by stsp** [comment]
You can also try freecom+ms-dos,
or comcom64+ms-dos.
Btw, I think it would be nice to have
the comcom64 CI tests running under
various DOSes.

**Comment by andrewbird** [comment]
> Also is it only ms-dos, or any non-fdpp dos?

It fails under MS-DOS 6.22 and DRDOS 7.01, but is okay with FreeDOS 1.3 and FDPP.

**Comment by stsp** [comment]
Can you make a test-case?
