### ISSUE TITLE
cannot dlopen /dev/shm/dosemu_COMMAND.COM: /usr/local/i386-pc-dj64/lib64/libdj64.so.0.2: undefined symbol: ___stdio_cleanup_proc

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/comcom64#98]
I am getting this error on my Debian i386 system:
```
cannot dlopen /dev/shm/dosemu_COMMAND.COM: /usr/local/i386-pc-dj64/lib64/libdj64.so.0.2: undefined symbol: ___stdio_cleanup_proc
```

I wasn't sure whether this would be an issue in comcom or maybe dj64? (Everything runs fine when I use command.com from FreeDOS.)

**Comment by stsp** [comment]
I guess it would be better if you give me an ssh.

**Comment by jschwartzenberg** [comment]
Wrote you on Session.

**Comment by stsp** [comment]
Session and Signal are blocked in Russia.
Please use plain old e-mail. :)
(at yandex.ru)

**Comment by jschwartzenberg** [comment]
Use the SHA256 signature of the SSH server with https://www.boxentriq.com/code-breaking/vigenere-cipher to decrypt the password.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jschwartzenberg** [comment]
Indeed! Getting another error now, but I'll create a new issue.
