### ISSUE TITLE
Crash, possibly related to i386

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/comcom64#99]
When I start DOSEMU2 now, it results in this when trying to run comcom:
```
Process 0 starting: E:\command.com /e:384 /p /k %FDPP_AUTOEXEC% /M2
DPMI: Unhandled Exception 0e - Terminating Client
It is likely that dosemu is unstable now and should be rebooted

Shell E:\command.com exited with code 0xff
```

**Comment by stsp** [comment]
Should now be fixed.
Though can't test as I don't have root
privs on your ssh.

**Comment by jschwartzenberg** [comment]
I've installed the updated version. Now I get this
```
shm_open(): Permission denied
ERROR: shared memory unavailable, exiting
```

**Comment by stsp** [comment]
I run `dosemu -dumb` on your machine
w/o any problems. How is so?

**Comment by jschwartzenberg** [comment]
Yeah, that's odd. Indeed it all works now! Many thanks!!
I think 32-bit support is fully ready for downstreaming into Debian :)

**Comment by jschwartzenberg** [comment]
![image](https://github.com/user-attachments/assets/c62ca3bf-34d1-40e9-b8c4-1c22e39f706c)
